### ISSUE TITLE
Was just passing by - what do you think of Vega as a tool for Data VIZ newbies? 

### ISSUE THREAD

**Issue by Casyfill** [amandabee/CUNY-data-storytelling#3]
no offence, just was wondering - in my experience teaching `js`  to complete newbies was a journey of it's own

**Comment by amandabee** [comment]
I've never tried Vega and a web search turned up a bunch of things that aren't data viz tools. Happy to take a look if you've got a URL. :)

**Comment by Casyfill** [comment]
I meant [this vega](https://vega.github.io/vega/) and the [whole family](https://vega.github.io/)
We've been using it for a while now at StreetEasy, and, having some experience in infographics and dataviz, I think it might help a lot if you're a newbie (or just need to do stuff faster)

**Comment by amandabee** [comment]
At a glance, it looks like a great resource. What I like about Highcharts is that there are a lot of good examples to start from, and the documentation is super clear. Vega seems to meet those requirements. thanks for the tip.
